name: 'Bundle Stats PR Commenter'
description:
  'Analyze webpack bundle stats and post size reports to pull requests'
author: 'yk-lab'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  stats-path:
    description: 'Path to webpack-stats.json file'
    required: false
    default: 'webpack-stats.json'
  bundle-size-threshold:
    description: 'Individual file size threshold in bytes'
    required: false
    default: '2097152' # 2MB
  total-size-threshold:
    description: 'Total bundle size threshold in bytes'
    required: false
    default: '10485760' # 10MB
  fail-on-threshold-exceed:
    description: 'Whether to fail the CI when thresholds are exceeded'
    required: false
    default: 'true'

outputs:
  comment-body:
    description: 'The markdown content of the posted/updated comment'
  exceeded:
    description: 'Boolean string indicating if any thresholds were exceeded'
  badge-svg:
    description: 'SVG content for the bundle size badge'

runs:
  using: node20
  main: dist/index.js
